kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
- role: control-plane
- role: control-plane
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 30000 # porta do container
    hostPort: 8081 # Porta que vai ser disponibilizada na maquina
- role: worker
- role: worker

