kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/16"
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
    ---
    kind: ClusterConfiguration
    etcd:
      local:
        extraArgs:
          "heartbeat-interval": "250"
          "election-timeout": "1250"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
    ---
    kind: ClusterConfiguration
    etcd:
      local:
        extraArgs:
          "heartbeat-interval": "250"
          "election-timeout": "1250"
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
    ---
    kind: ClusterConfiguration
    etcd:
      local:
        extraArgs:
          "heartbeat-interval": "250"
          "election-timeout": "1250"
- role: worker
- role: worker