apiVersion: v1
kind: Service
metadata:
  name: app-helpdesk
  labels:
    app: app-helpdesk
spec:
  type: ClusterIP  # Expor o serviço internamente no cluster
  ports:
    - port: 80
      targetPort: 8080  # Porta que o container está escutando
  selector:
    app: app-helpdesk  # O seletor garante que o tráfego seja direcionado para o pod correto
